export const environment = {
  production: false,
  root: "/root",
  apiUrl: "/apiUrl",
  apiConUrl: "apiConUrl",
  apiReportUrl: "apiReportUrl",
  apiDonwUrl: "apiDonwUrl",
  his: "dev",
  authenticationUrl: "https://url-api.auth/login",
  authorizationUrl: "yoru-URL",
  clientIdMSAL: "xxxxx",
  authorityMSAL: "https://login.microsoftonline.com/xxxxx",
  redirectUriMSAL: "localhost_URL",
  devProxy: true,
};
